name: First Workflow

on: push

jobs:
  hello:
    runs-on: windows-latest
    steps:
      - run: echo "hello from Github Actions"
  

  test:
    runs-on: windows-latest
    steps:
      -name:checkout code
       uses: actions/checkout@v4

      -name: setup python
       uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      -name: Install dependencies
        run: pip install -r requirements.txt

      -name: run tests
        run: pytest
